# Generated by Django 4.1.1 on 2022-09-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('contactnum', models.CharField(max_length=255)),
                ('dateenrolled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
