# Generated by Django 4.1.1 on 2022-09-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='estatus',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
