# Generated by Django 4.1.1 on 2022-09-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='estatus',
        ),
        migrations.AddField(
            model_name='student',
            name='estatus',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
